name: pattern
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  intl: ^0.20.2
  package_info_plus: ^8.1.0
  provider: ^6.1.2
  webview_flutter: ^4.10.0
  file_picker: ^8.1.6
  path: ^1.9.0
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.2
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/flutter_logo.png"
  android: true
  ios: true
  web: true

flutter_icons:
  image_path: "assets/images/app_logo.png"
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
